# Copyright (c) 2025 Ronan Le Meillat - SCTG Development

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Create Release with Augmented Data

on:
  workflow_dispatch:

jobs:
  process-departments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ["auvergne-rhone-alpes", "bourgogne-franche-comte", "bretagne", "centre-val-de-loire", "corse", "grand-est", "hauts-de-france", "ile-de-france", "normandie", "nouvelle-aquitaine", "occitanie", "pays-de-la-loire", "provence-alpes-cote-d-azur"]
        include:
          - region: "auvergne-rhone-alpes"
            departments: "001,003,007,015,026,038,042,043,063,069,073,074"
            name: "Auvergne-Rhône-Alpes"
          - region: "bourgogne-franche-comte"
            departments: "021,025,039,058,070,071,089,090"
            name: "Bourgogne-Franche-Comté"
          - region: "bretagne"
            departments: "022,029,035,056"
            name: "Bretagne"
          - region: "centre-val-de-loire"
            departments: "018,028,036,037,041,045"
            name: "Centre-Val de Loire"
          - region: "corse"
            departments: "02A,02B"
            name: "Corse"
          - region: "grand-est"
            departments: "008,010,051,052,054,055,057,067,068,088"
            name: "Grand Est"
          - region: "hauts-de-france"
            departments: "002,059,060,062,080"
            name: "Hauts-de-France"
          - region: "ile-de-france"
            departments: "075,077,078,091,092,093,094,095"
            name: "Île-de-France"
          - region: "normandie"
            departments: "014,027,050,061,076"
            name: "Normandie"
          - region: "nouvelle-aquitaine"
            departments: "016,017,019,023,024,033,040,047,064,079,086,087"
            name: "Nouvelle-Aquitaine"
          - region: "occitanie"
            departments: "009,011,030,031,032,034,046,048,065,066,081,082"
            name: "Occitanie"
          - region: "pays-de-la-loire"
            departments: "044,049,053,072,085"
            name: "Pays de la Loire"
          - region: "provence-alpes-cote-d-azur"
            departments: "004,005,006,013,083,084"
            name: "Provence-Alpes-Côte d'Azur"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests numpy geopandas

    - name: Cache BRGM downloads and tiles
      uses: actions/cache@v4
      with:
        path: |
          temp
        key: brgm-cache-${{ matrix.region }}-${{ hashFiles('**/add_altitude.py') }}
        restore-keys: |
          brgm-cache-${{ matrix.region }}-
          brgm-cache-

    - name: Create output directory
      run: mkdir -p output_${{ matrix.region }}

    - name: Run altitude augmentation script for ${{ matrix.name }}
      run: |
        python add_altitude.py --from-brgm --out output_${{ matrix.region }} --departments ${{ matrix.departments }} --temp-dir temp

    - name: Upload processed ZIPs
      uses: actions/upload-artifact@v4
      with:
        name: brgm-data-${{ matrix.region }}
        path: output_${{ matrix.region }}/*.zip

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      attestations: write
      id-token: write
    needs: process-departments

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download all processed ZIPs
      uses: actions/download-artifact@v4
      with:
        path: all_zips

    - name: Generate ISO8601 date
      id: date
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

    - name: Flatten ZIP files
      run: |
        cd all_zips
        find . -name "*.zip" -exec mv {} . \;
        rm -rf brgm-data-*
        ls -la *.zip

    - name: Handle combined departments
      run: |
        cd all_zips
        mv GEO050K_HARM_062.zip GEO050K_HARM_059_062.zip
        mv GEO050K_HARM_095.zip GEO050K_HARM_075_077_078_091_092_093_094_095.zip

    - name: Generate build provenance attestations
      uses: actions/attest-build-provenance@v1
      continue-on-error: true
      with:
        subject-path: all_zips/*.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.date.outputs.date }}
        name: Geological Data with Altitude - ${{ steps.date.outputs.date }}
        body: |
          This release contains BRGM geological data for all French administrative regions augmented with altitude information from IGN.

          Each region is provided as a separate ZIP file for individual download.

          ## Coverage
          - **Auvergne-Rhône-Alpes**: 12 departments
          - **Bourgogne-Franche-Comté**: 8 departments
          - **Bretagne**: 4 departments
          - **Centre-Val de Loire**: 6 departments
          - **Corse**: 2 departments
          - **Grand Est**: 10 departments
          - **Hauts-de-France**: 5 departments
          - **Île-de-France**: 8 departments
          - **Normandie**: 5 departments
          - **Nouvelle-Aquitaine**: 12 departments
          - **Occitanie**: 12 departments
          - **Pays de la Loire**: 5 departments
          - **Provence-Alpes-Côte d'Azur**: 6 departments

          **Total**: All 96 French departments with geological point data enhanced with elevation data.

          ## Download Options
          - Download individual region ZIP files (recommended for bandwidth efficiency)
          - Each ZIP file contains all geological data for that region with altitude information added

          ## Data Format
          Each ZIP file contains shapefiles with the following attributes:
          - All original BRGM attributes
          - **ALTITUDE**: Elevation in meters (from IGN WMS service, 25m resolution)

          ## Notes
          - Files are compressed using ZIP format with deflate compression
          - Each department's data is included in the regional ZIP files
          - Coordinates are in EPSG:2154 (Lambert 93, France-specific projection)
        files: |
          all_zips/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}